# Generated by Django 3.0.7 on 2020-06-13 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('close_date', models.DateField(help_text='The last day on which the post is visible on the homepage')),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('video_id', models.CharField(max_length=64)),
                ('upload_datetime', models.DateTimeField()),
                ('show_on_website', models.BooleanField()),
            ],
            options={
                'verbose_name': 'YouTube video',
                'verbose_name_plural': 'YouTube videos',
            },
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Post')),
                ('gig_start_date', models.DateField()),
                ('gig_start_time', models.TimeField(blank=True, null=True)),
                ('gig_end_date', models.DateField(blank=True, null=True)),
                ('gig_end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=64)),
                ('google_maps_link', models.CharField(blank=True, max_length=256)),
                ('ticket_link', models.CharField(blank=True, max_length=256)),
            ],
            bases=('website.post',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Post')),
                ('short_description', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
            bases=('website.post',),
        ),
    ]
