# Generated by Django 3.0.7 on 2020-06-09 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Post')),
                ('gig_start_date', models.DateField()),
                ('gig_start_time', models.TimeField(blank=True, null=True)),
                ('gig_end_date', models.DateField(blank=True, null=True)),
                ('gig_end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=64)),
                ('google_maps_link', models.CharField(blank=True, max_length=256)),
                ('ticket_link', models.CharField(blank=True, max_length=256)),
            ],
            bases=('website.post',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Post')),
                ('short_description', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
            bases=('website.post',),
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'verbose_name': 'YouTube video', 'verbose_name_plural': 'YouTube videos'},
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
