# Generated by Django 3.0.7 on 2020-06-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_gigs_and_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='close_date',
            field=models.DateField(help_text='The last day on which the post is visible on the website'),
        ),
    ]
