# Generated by Django 3.0.11 on 2021-04-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=256)),
                ('image', models.ImageField(help_text='For best result, always upload images with 1:1 aspect ratio', upload_to='links')),
                ('close_date', models.DateField(blank=True, help_text='The last day on which the link is visible on the linkpage', null=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField(editable=False)),
            ],
        ),
    ]
