# Generated by Django 3.0.11 on 2021-04-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='open_date',
            field=models.DateField(blank=True, help_text='The first day on which the link will be visible on the linkpage', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='close_date',
            field=models.DateField(blank=True, help_text='The last day on which the link will be visible on the linkpage', null=True),
        ),
    ]
