# Generated by Django 3.0.11 on 2021-05-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkpage', '0002_auto_20210424_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='alt_url',
            field=models.CharField(blank=True, help_text='Provide an alternative url, if original url does not use http or https protocol', max_length=256, null=True, verbose_name='Alternative Url'),
        ),
    ]
