# Generated by Django 3.0.7 on 2020-06-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=32, unique=True)),
                ('redirect_url', models.CharField(max_length=256)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('modified_at', models.DateTimeField(editable=False)),
            ],
        ),
    ]
