# Generated by Django 3.0.7 on 2020-06-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liliput', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='number_of_requests',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortlink',
            name='verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
