# Generated by Django 3.0.7 on 2020-10-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liliput', '0002_verify_and_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_url',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
